name: Homebrew Installation

on:
  push:
    paths-ignore:
      '*.md'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master

jobs:

  intel:
    name: Validate intel
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: test in the installations
        run: |
          brew install --cask Casks/redis-stack-server.rb
          brew install --cask Casks/redis-stack-redisinsight.rb
      - name: run redis-stack
        run:
          /usr/local/bin/redis-stack-server -h &
      - name: try to redis-stack
        run:
          redis-cli ping

  m1:
    name: Validate arm64
    runs-on: macos-14 # TODO: investigate why latest does not represent macos 14
    steps:
      - uses: actions/checkout@v3
      - name: test in the installations
        run: |
          brew install --cask Casks/redis-stack-server.rb
          brew install --cask Casks/redis-stack-redisinsight.rb
      - name: run redis-stack
        run:
          /opt/homebrew/bin/redis-stack-server -h &
      - name: try to redis-stack
        run:
          redis-cli ping
